// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        (unknown)
// source: api/proto/sqs.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SqsMessageBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Records []*SqsMessageBodyRecord `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
}

func (x *SqsMessageBody) Reset() {
	*x = SqsMessageBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_sqs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SqsMessageBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SqsMessageBody) ProtoMessage() {}

func (x *SqsMessageBody) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sqs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SqsMessageBody.ProtoReflect.Descriptor instead.
func (*SqsMessageBody) Descriptor() ([]byte, []int) {
	return file_api_proto_sqs_proto_rawDescGZIP(), []int{0}
}

func (x *SqsMessageBody) GetRecords() []*SqsMessageBodyRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type SqsMessageBodyRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventVersion string        `protobuf:"bytes,1,opt,name=eventVersion,proto3" json:"eventVersion,omitempty"`
	EventSource  string        `protobuf:"bytes,2,opt,name=eventSource,proto3" json:"eventSource,omitempty"`
	AwsRegion    string        `protobuf:"bytes,3,opt,name=awsRegion,proto3" json:"awsRegion,omitempty"`
	EventTime    string        `protobuf:"bytes,4,opt,name=eventTime,proto3" json:"eventTime,omitempty"`
	EventName    string        `protobuf:"bytes,5,opt,name=eventName,proto3" json:"eventName,omitempty"`
	UserIdentity *UserIdentity `protobuf:"bytes,6,opt,name=userIdentity,proto3" json:"userIdentity,omitempty"`
	S3           *S3           `protobuf:"bytes,9,opt,name=s3,proto3" json:"s3,omitempty"`
}

func (x *SqsMessageBodyRecord) Reset() {
	*x = SqsMessageBodyRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_sqs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SqsMessageBodyRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SqsMessageBodyRecord) ProtoMessage() {}

func (x *SqsMessageBodyRecord) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sqs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SqsMessageBodyRecord.ProtoReflect.Descriptor instead.
func (*SqsMessageBodyRecord) Descriptor() ([]byte, []int) {
	return file_api_proto_sqs_proto_rawDescGZIP(), []int{1}
}

func (x *SqsMessageBodyRecord) GetEventVersion() string {
	if x != nil {
		return x.EventVersion
	}
	return ""
}

func (x *SqsMessageBodyRecord) GetEventSource() string {
	if x != nil {
		return x.EventSource
	}
	return ""
}

func (x *SqsMessageBodyRecord) GetAwsRegion() string {
	if x != nil {
		return x.AwsRegion
	}
	return ""
}

func (x *SqsMessageBodyRecord) GetEventTime() string {
	if x != nil {
		return x.EventTime
	}
	return ""
}

func (x *SqsMessageBodyRecord) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *SqsMessageBodyRecord) GetUserIdentity() *UserIdentity {
	if x != nil {
		return x.UserIdentity
	}
	return nil
}

func (x *SqsMessageBodyRecord) GetS3() *S3 {
	if x != nil {
		return x.S3
	}
	return nil
}

type UserIdentity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrincipalId string `protobuf:"bytes,1,opt,name=principalId,proto3" json:"principalId,omitempty"`
}

func (x *UserIdentity) Reset() {
	*x = UserIdentity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_sqs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIdentity) ProtoMessage() {}

func (x *UserIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sqs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIdentity.ProtoReflect.Descriptor instead.
func (*UserIdentity) Descriptor() ([]byte, []int) {
	return file_api_proto_sqs_proto_rawDescGZIP(), []int{2}
}

func (x *UserIdentity) GetPrincipalId() string {
	if x != nil {
		return x.PrincipalId
	}
	return ""
}

type S3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	S3SchemaVersion string    `protobuf:"bytes,1,opt,name=s3SchemaVersion,proto3" json:"s3SchemaVersion,omitempty"`
	ConfigurationId string    `protobuf:"bytes,2,opt,name=configurationId,proto3" json:"configurationId,omitempty"`
	Bucket          *S3Bucket `protobuf:"bytes,3,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Object          *S3Object `protobuf:"bytes,4,opt,name=object,proto3" json:"object,omitempty"`
}

func (x *S3) Reset() {
	*x = S3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_sqs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3) ProtoMessage() {}

func (x *S3) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sqs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3.ProtoReflect.Descriptor instead.
func (*S3) Descriptor() ([]byte, []int) {
	return file_api_proto_sqs_proto_rawDescGZIP(), []int{3}
}

func (x *S3) GetS3SchemaVersion() string {
	if x != nil {
		return x.S3SchemaVersion
	}
	return ""
}

func (x *S3) GetConfigurationId() string {
	if x != nil {
		return x.ConfigurationId
	}
	return ""
}

func (x *S3) GetBucket() *S3Bucket {
	if x != nil {
		return x.Bucket
	}
	return nil
}

func (x *S3) GetObject() *S3Object {
	if x != nil {
		return x.Object
	}
	return nil
}

type S3Bucket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	OwnerIdentity *UserIdentity `protobuf:"bytes,2,opt,name=ownerIdentity,proto3" json:"ownerIdentity,omitempty"`
	Arn           string        `protobuf:"bytes,3,opt,name=arn,proto3" json:"arn,omitempty"`
}

func (x *S3Bucket) Reset() {
	*x = S3Bucket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_sqs_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S3Bucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3Bucket) ProtoMessage() {}

func (x *S3Bucket) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sqs_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3Bucket.ProtoReflect.Descriptor instead.
func (*S3Bucket) Descriptor() ([]byte, []int) {
	return file_api_proto_sqs_proto_rawDescGZIP(), []int{4}
}

func (x *S3Bucket) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *S3Bucket) GetOwnerIdentity() *UserIdentity {
	if x != nil {
		return x.OwnerIdentity
	}
	return nil
}

func (x *S3Bucket) GetArn() string {
	if x != nil {
		return x.Arn
	}
	return ""
}

type S3Object struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key       string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Sequencer string `protobuf:"bytes,2,opt,name=sequencer,proto3" json:"sequencer,omitempty"`
	VersionId string `protobuf:"bytes,3,opt,name=versionId,proto3" json:"versionId,omitempty"`
	Size      int64  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	ETag      string `protobuf:"bytes,5,opt,name=eTag,proto3" json:"eTag,omitempty"`
}

func (x *S3Object) Reset() {
	*x = S3Object{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_sqs_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S3Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3Object) ProtoMessage() {}

func (x *S3Object) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_sqs_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3Object.ProtoReflect.Descriptor instead.
func (*S3Object) Descriptor() ([]byte, []int) {
	return file_api_proto_sqs_proto_rawDescGZIP(), []int{5}
}

func (x *S3Object) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *S3Object) GetSequencer() string {
	if x != nil {
		return x.Sequencer
	}
	return ""
}

func (x *S3Object) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

func (x *S3Object) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *S3Object) GetETag() string {
	if x != nil {
		return x.ETag
	}
	return ""
}

var File_api_proto_sqs_proto protoreflect.FileDescriptor

var file_api_proto_sqs_proto_rawDesc = []byte{
	0x0a, 0x13, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x71, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x61, 0x72, 0x72, 0x61, 0x6b, 0x69, 0x73, 0x2e, 0x61,
	0x77, 0x73, 0x22, 0x4d, 0x0a, 0x0e, 0x53, 0x71, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x42, 0x6f, 0x64, 0x79, 0x12, 0x3b, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x61, 0x72, 0x72, 0x61, 0x6b, 0x69, 0x73, 0x2e,
	0x61, 0x77, 0x73, 0x2e, 0x53, 0x71, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x6f,
	0x64, 0x79, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x73, 0x22, 0x96, 0x02, 0x0a, 0x14, 0x53, 0x71, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x42, 0x6f, 0x64, 0x79, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x20,
	0x0a, 0x0b, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x61, 0x77, 0x73, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x77, 0x73, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x1c,
	0x0a, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x3d, 0x0a, 0x0c, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x61, 0x72, 0x72, 0x61, 0x6b, 0x69, 0x73, 0x2e, 0x61, 0x77, 0x73, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x0c, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x1f, 0x0a, 0x02, 0x73, 0x33, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x72, 0x72, 0x61, 0x6b, 0x69, 0x73, 0x2e,
	0x61, 0x77, 0x73, 0x2e, 0x53, 0x33, 0x52, 0x02, 0x73, 0x33, 0x22, 0x30, 0x0a, 0x0c, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x72,
	0x69, 0x6e, 0x63, 0x69, 0x70, 0x61, 0x6c, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x70, 0x72, 0x69, 0x6e, 0x63, 0x69, 0x70, 0x61, 0x6c, 0x49, 0x64, 0x22, 0xb6, 0x01, 0x0a,
	0x02, 0x53, 0x33, 0x12, 0x28, 0x0a, 0x0f, 0x73, 0x33, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x73, 0x33,
	0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x0a,
	0x0f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x2d, 0x0a, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x72, 0x72, 0x61, 0x6b, 0x69,
	0x73, 0x2e, 0x61, 0x77, 0x73, 0x2e, 0x53, 0x33, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x06,
	0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x2d, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x72, 0x72, 0x61, 0x6b, 0x69, 0x73,
	0x2e, 0x61, 0x77, 0x73, 0x2e, 0x53, 0x33, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x06, 0x6f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x22, 0x71, 0x0a, 0x08, 0x53, 0x33, 0x42, 0x75, 0x63, 0x6b, 0x65,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x3f, 0x0a, 0x0d, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61,
	0x72, 0x72, 0x61, 0x6b, 0x69, 0x73, 0x2e, 0x61, 0x77, 0x73, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x0d, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x72, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x72, 0x6e, 0x22, 0x80, 0x01, 0x0a, 0x08, 0x53, 0x33, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x71, 0x75, 0x65,
	0x6e, 0x63, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x71, 0x75,
	0x65, 0x6e, 0x63, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x65, 0x54, 0x61, 0x67, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x65, 0x54, 0x61, 0x67, 0x42, 0x73, 0x0a, 0x0f, 0x63,
	0x6f, 0x6d, 0x2e, 0x61, 0x72, 0x72, 0x61, 0x6b, 0x69, 0x73, 0x2e, 0x61, 0x77, 0x73, 0x42, 0x08,
	0x53, 0x71, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x09, 0x61, 0x70, 0x69, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0xa2, 0x02, 0x03, 0x41, 0x41, 0x58, 0xaa, 0x02, 0x0b, 0x41, 0x72,
	0x72, 0x61, 0x6b, 0x69, 0x73, 0x2e, 0x41, 0x77, 0x73, 0xca, 0x02, 0x0b, 0x41, 0x72, 0x72, 0x61,
	0x6b, 0x69, 0x73, 0x5c, 0x41, 0x77, 0x73, 0xe2, 0x02, 0x17, 0x41, 0x72, 0x72, 0x61, 0x6b, 0x69,
	0x73, 0x5c, 0x41, 0x77, 0x73, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0xea, 0x02, 0x0c, 0x41, 0x72, 0x72, 0x61, 0x6b, 0x69, 0x73, 0x3a, 0x3a, 0x41, 0x77, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_sqs_proto_rawDescOnce sync.Once
	file_api_proto_sqs_proto_rawDescData = file_api_proto_sqs_proto_rawDesc
)

func file_api_proto_sqs_proto_rawDescGZIP() []byte {
	file_api_proto_sqs_proto_rawDescOnce.Do(func() {
		file_api_proto_sqs_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_sqs_proto_rawDescData)
	})
	return file_api_proto_sqs_proto_rawDescData
}

var file_api_proto_sqs_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_sqs_proto_goTypes = []interface{}{
	(*SqsMessageBody)(nil),       // 0: arrakis.aws.SqsMessageBody
	(*SqsMessageBodyRecord)(nil), // 1: arrakis.aws.SqsMessageBodyRecord
	(*UserIdentity)(nil),         // 2: arrakis.aws.UserIdentity
	(*S3)(nil),                   // 3: arrakis.aws.S3
	(*S3Bucket)(nil),             // 4: arrakis.aws.S3Bucket
	(*S3Object)(nil),             // 5: arrakis.aws.S3Object
}
var file_api_proto_sqs_proto_depIdxs = []int32{
	1, // 0: arrakis.aws.SqsMessageBody.records:type_name -> arrakis.aws.SqsMessageBodyRecord
	2, // 1: arrakis.aws.SqsMessageBodyRecord.userIdentity:type_name -> arrakis.aws.UserIdentity
	3, // 2: arrakis.aws.SqsMessageBodyRecord.s3:type_name -> arrakis.aws.S3
	4, // 3: arrakis.aws.S3.bucket:type_name -> arrakis.aws.S3Bucket
	5, // 4: arrakis.aws.S3.object:type_name -> arrakis.aws.S3Object
	2, // 5: arrakis.aws.S3Bucket.ownerIdentity:type_name -> arrakis.aws.UserIdentity
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_api_proto_sqs_proto_init() }
func file_api_proto_sqs_proto_init() {
	if File_api_proto_sqs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_sqs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SqsMessageBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_sqs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SqsMessageBodyRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_sqs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserIdentity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_sqs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_sqs_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S3Bucket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_sqs_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S3Object); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_sqs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_sqs_proto_goTypes,
		DependencyIndexes: file_api_proto_sqs_proto_depIdxs,
		MessageInfos:      file_api_proto_sqs_proto_msgTypes,
	}.Build()
	File_api_proto_sqs_proto = out.File
	file_api_proto_sqs_proto_rawDesc = nil
	file_api_proto_sqs_proto_goTypes = nil
	file_api_proto_sqs_proto_depIdxs = nil
}
